# Generated by Django 4.2.15 on 2024-10-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarbonFootprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cropclass", models.CharField(max_length=255)),
                ("cropbrick", models.CharField(max_length=255)),
                ("cropname", models.CharField(max_length=255)),
                ("sourcedb_name", models.CharField(max_length=255)),
                ("source_db_id", models.CharField(max_length=255)),
                ("lifecycle_stage", models.CharField(max_length=255)),
                ("origin_region", models.CharField(max_length=255)),
                ("applicable_region", models.CharField(max_length=255)),
                ("production_system", models.CharField(max_length=255)),
                ("factor_kg_co2e", models.FloatField()),
                ("func_unit", models.CharField(max_length=255)),
                ("factor_type", models.CharField(max_length=255)),
                ("data_quality_score", models.CharField(max_length=255)),
            ],
        ),
    ]
