# Generated by Django 4.2.15 on 2024-10-11 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carbonfootprint", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carbonfootprint",
            options={
                "ordering": [
                    "cropname",
                    "sourcedb_name",
                    "lifecycle_stage",
                    "origin_region",
                    "applicable_region",
                    "production_system",
                    "factor_kg_co2e",
                    "func_unit",
                ]
            },
        ),
    ]
